#!/bin/bash
source secrets

if [ ! -d "v" ]; then
    virtualenv v/;
    cd generator; ../v/bin/pip install -e .; cd ../;
    v/bin/pip install -r requirements.txt;
fi;

v/bin/python generator/generator/generate_site.py $(pwd) "$@"
